
package com.tigerjoys.panda.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationWebService", targetNamespace = "http://ws.panda.tigerjoys.com/", wsdlLocation = "http://panda.didiman.com:82/Panda/LocationWebService?wsdl")
public class LocationWebService_Service
    extends Service
{

    private final static URL LOCATIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONWEBSERVICE_EXCEPTION;
    private final static QName LOCATIONWEBSERVICE_QNAME = new QName("http://ws.panda.tigerjoys.com/", "LocationWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://panda.didiman.com:82/Panda/LocationWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONWEBSERVICE_WSDL_LOCATION = url;
        LOCATIONWEBSERVICE_EXCEPTION = e;
    }

    public LocationWebService_Service() {
        super(__getWsdlLocation(), LOCATIONWEBSERVICE_QNAME);
    }

    public LocationWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONWEBSERVICE_QNAME, features);
    }

    public LocationWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONWEBSERVICE_QNAME);
    }

    public LocationWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONWEBSERVICE_QNAME, features);
    }

    public LocationWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocationWebService
     */
    @WebEndpoint(name = "LocationWebServicePort")
    public LocationWebService getLocationWebServicePort() {
        return super.getPort(new QName("http://ws.panda.tigerjoys.com/", "LocationWebServicePort"), LocationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationWebService
     */
    @WebEndpoint(name = "LocationWebServicePort")
    public LocationWebService getLocationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.panda.tigerjoys.com/", "LocationWebServicePort"), LocationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONWEBSERVICE_EXCEPTION!= null) {
            throw LOCATIONWEBSERVICE_EXCEPTION;
        }
        return LOCATIONWEBSERVICE_WSDL_LOCATION;
    }

}
